# Generated by Django 3.0.3 on 2020-03-23 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='comments',
        ),
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
