# Generated by Django 3.0.3 on 2020-04-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20200403_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.TextField(max_length=3),
        ),
    ]
