"""
Django settings for ShoeWeb project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ojqt7!+u0bis3-iqwayq_!wb6xwem)^ky-e9u^su-@1g1a-iwb'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home.apps.HomeConfig',
    'crispy_forms',
    'search_app.apps.SearchAppConfig',
    'cart.apps.CartConfig',
    'vouchers.apps.VouchersConfig',
    'order.apps.OrderConfig',
    'contactEmail.apps.ContactemailConfig',
    'django_filters',
    'jquery',
    'django_simple_coupons',
    'localflavor',
    'stripe',
    'captcha',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ShoeWeb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'),
                os.path.join(BASE_DIR,'cart','templates/'),
                os.path.join(BASE_DIR,'order','templates/')    ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processors.cart',
            ],
        },
    },
]

WSGI_APPLICATION = 'ShoeWeb.wsgi.application'

# email backend
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_Host = 'smtp.gmail.com'
EMAIL_Host_USER = ''
EMAIL_Host_PASSWORD = ''
EMAIL_PORT = 587
EMAIL_USE_TLS = True


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'assets'),
)

CRISPY_TEMPLATE_PACK = 'bootstrap3'
CRISPY_TEMPLATE_PACK = 'bootstrap4'

LOGIN_REDIRECT_URL = '/'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

LOGIN_URL = '/account/login/'

CART_SESSION_ID = 'cart'
STRIPE_PUBLISHABLE_KEY = 'pk_test_ox4IkFUhPnLRLsQSfVDyou8300fsrsNwbT'
STRIPE_SECRET_KEY = 'sk_test_VWmZp2iKmOdzN7rJXsqWUCNL004UXCzgOt'

RECAPTCHA_PUBLIC_KEY = '6LdaV-UUAAAAACJ3HkCTtcJQiYSrRwhvRRnxm4UJ'
GOOGLE_RECAPTCHA_SECRET_KEY = '6LdaV-UUAAAAALToTiKXwafWb5_m2jlpufK3tAEh'
SILENCED_SYSTEM_CHECKS = ['captcha.recaptcha_test_key_error']

FROM_EMAIL = 'emmanuel.ad5648@gmail.com' # replace with your address
SENDGRID_API_KEY = ('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')
EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = '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'